export { answers } from './answers'
export { profiles } from './profiles'
export { questions } from './questions'
export { schools } from './schools'
export { scores } from './score'
export { students } from './students'
export { subjects } from './subjects'
export { teachers } from './teachers'
export { tests } from './test'
export { userStudents, userTeachers } from './users'
