export { authController } from './auth'
export { questionController } from './question'
export { schoolController } from './school'
export { studentController } from './student'
export { subjectController } from './subject'
export { teacherController } from './teacher'
export { testController } from './test'
